---
author: admin
categories: app
date: '2010-11-25 23:07:20'
developer: VirtualDesign
developer_link: http://www.cyrket.com/p/android/real.decisionball/
devices: 
- android
permalink: /app/real-decision-ball/
slug: real-decision-ball
status: publish
thumb: http://cache.cyrket.com/p/android/real.decisionball/icon
title: Real Decision Ball
type: app
---

All of the other balls use PseudoRandomNumbers generated by CPU with mathematical formulas. Our Ball generates TrueRandomNumbers, analyzing radio waves of your phone. This is first time in your life when your future is in hands of a mystical power of randomness, not controlled by computer!